modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/CookingForBlockheads/issues"

[[mods]]
modId="cookingforblockheads"
version="${mod_version}"
displayName="CookingForBlockheads"
displayURL="https://mods.twelveiterations.com/mc/cookingforblockheads"
logoFile="cookingforblockheads-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a cooking book and multiblock kitchens that only shows recipes you can make with what you currently have in your inventory.
'''

[[dependencies.cookingforblockheads]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.cookingforblockheads]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.cookingforblockheads]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
